# Generated by Django 4.2.6 on 2024-07-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_alter_animal_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='animais/'),
        ),
    ]
